export type UiLanguage = "ru" | "en";

const RU_TO_EN: Record<string, string> = {
  "ROXY — главная": "ROXY — Home",
  "ROXY загружается": "ROXY is loading",
  "Студия творчества": "Creative studio",
  "Баланс": "Balance",
  "Бесплатно": "Free",
  "Бонус": "Bonus",
  "Бонус за приглашение": "Referral bonus",
  "Быстрый старт": "Quick start",
  "В ленту + профиль": "Feed + profile",
  "В очереди": "Queued",
  "В профиль": "To profile",
  "В работе": "In progress",
  "Ваш комментарий": "Your comment",
  "Видео": "Video",
  "Возврат": "Refund",
  "Возвращено": "Refunded",
  "Все": "All",
  "Все работы": "All works",
  "Выберите модель": "Choose a model",
  "Выберите пакет": "Choose a package",
  "Генерация запущена. ROXY можно закрыть — результат придёт в Telegram.": "Generation started. You can close ROXY — the result will arrive in Telegram.",
  "Готовим": "Preparing",
  "Готовлю оплату…": "Preparing payment…",
  "Готово": "Ready",
  "Готовые работы появятся здесь.": "Finished works will appear here.",
  "Готовые сценарии": "Ready-made scenarios",
  "Готовый сценарий": "Ready-made scenario",
  "Готовых работ пока нет.": "No finished works yet.",
  "Делитесь ссылкой, приглашайте друзей и отслеживайте бонусы в одном месте.": "Share your link, invite friends, and track bonuses in one place.",
  "Длительность": "Duration",
  "Для этого тренда нужен пример. Скоро откроем удобную форму.": "This trend needs a reference. A convenient upload form is coming soon.",
  "Добавьте хотя бы один референс": "Add at least one reference",
  "Доступно": "Available",
  "Доход": "Earnings",
  "Ждёт": "Pending",
  "Загрузите свои референсы для повтора": "Upload your own references to repeat this",
  "Закрыть": "Close",
  "Заполните обязательное поле": "Fill in the required field",
  "Запускается": "Starting",
  "Запускаю…": "Starting…",
  "Здесь собраны готовые работы и то, что ещё создаётся.": "Finished works and generations in progress are collected here.",
  "Использовать настройки": "Use settings",
  "История": "History",
  "История пока пуста.": "History is empty.",
  "Кабинет автора": "Creator dashboard",
  "Каталог": "Catalog",
  "Каталог моделей загружается": "Model catalog is loading",
  "Комментариев пока нет.": "No comments yet.",
  "Комментарии": "Comments",
  "Корректировка": "Adjustment",
  "Лайк": "Like",
  "Лайк есть": "Liked",
  "Лента": "Feed",
  "Лента пока пуста. Опубликуйте работу в предпросмотре.": "The feed is empty. Publish a work from preview.",
  "Модели": "Models",
  "Модель": "Model",
  "Моя работа": "My work",
  "Музыка": "Music",
  "Настройки": "Settings",
  "Начните с готового сценария или выберите модель под свою идею.": "Start with a ready-made scenario or choose a model for your idea.",
  "Не получилось": "Failed",
  "Не удалось запустить генерацию": "Could not start generation",
  "Не удалось запустить тренд": "Could not start trend",
  "Не удалось опубликовать": "Could not publish",
  "Не удалось открыть комментарии": "Could not open comments",
  "Не удалось открыть работу": "Could not open work",
  "Не удалось отправить комментарий": "Could not send comment",
  "Не удалось перенести настройки": "Could not transfer settings",
  "Не удалось повторить": "Could not repeat",
  "Не удалось поделиться": "Could not share",
  "Не удалось поставить лайк": "Could not like",
  "Не удалось рассчитать цену": "Could not calculate price",
  "Не удалось рассчитать стоимость": "Could not calculate cost",
  "Не удалось создать платёж": "Could not create payment",
  "Не удалось убрать публикацию": "Could not remove publication",
  "Недавнее": "Recent",
  "Новая работа": "New work",
  "Новые": "New",
  "Новые приглашения": "New invitations",
  "Обновить": "Refresh",
  "Операция": "Operation",
  "Описание": "Description",
  "Опишите идею, добавьте примеры и выберите подходящий формат.": "Describe your idea, add references, and choose a format.",
  "Основная навигация": "Main navigation",
  "Откройте ROXY через Telegram-бота": "Open ROXY from the Telegram bot",
  "Открываю…": "Opening…",
  "Открыть ROXY": "Open ROXY",
  "Открыть результат": "Open result",
  "Отменено": "Canceled",
  "Отправить": "Send",
  "Отправляю…": "Sending…",
  "Ошибка загрузки": "Loading error",
  "Партнёрам": "For partners",
  "Партнёрские выплаты": "Partner payouts",
  "Партнёры": "Partners",
  "Перевод партнёра": "Partner transfer",
  "Перейти к оплате": "Proceed to payment",
  "Переношу…": "Transferring…",
  "Платёж создан": "Payment created",
  "Платёжная ссылка не получена": "Payment link was not received",
  "Повтор запущен": "Repeat started",
  "Повторяем": "Retrying",
  "Повторить": "Repeat",
  "Поделиться": "Share",
  "Поделиться профилем": "Share profile",
  "Полный каталог": "Full catalog",
  "Пользователь": "User",
  "Пополнение": "Top-up",
  "Последние движения": "Recent transactions",
  "Последние начисления": "Recent rewards",
  "Последние работы": "Latest works",
  "Предыдущий слайд": "Previous slide",
  "Приглашений пока нет.": "No invitations yet.",
  "Промо ROXY": "ROXY promos",
  "Промо для авторов": "Creator promo",
  "Промпт": "Prompt",
  "Профиль": "Profile",
  "Публикации": "Publications",
  "Публикаций пока нет. Открой работу и нажми “В профиль” или “В ленту + профиль”.": "No publications yet. Open a work and choose “To profile” or “Feed + profile”.",
  "Публикую…": "Publishing…",
  "Работа ROXY": "ROXY work",
  "Работа опубликована в ленте и профиле": "Work published to feed and profile",
  "Работа опубликована в профиле": "Work published to profile",
  "Работы": "Works",
  "Работы сообщества": "Community works",
  "Результат": "Result",
  "Рефералы": "Referrals",
  "Слайды промо": "Promo slides",
  "Следующий слайд": "Next slide",
  "Смотрите свежие идеи, сохраняйте понравившееся и повторяйте работы в своём стиле.": "Explore fresh ideas, save what you like, and recreate works in your own style.",
  "Создание": "Creation",
  "Создать": "Create",
  "Создаётся": "Generating",
  "Списание только в ROX": "Charged only in ROX",
  "Ссылка появится после входа в ROXY.": "The link will appear after you sign in to ROXY.",
  "Ссылка скопирована": "Link copied",
  "Студия": "Studio",
  "Студия для создания фото, видео и музыки.": "A studio for creating photos, videos, and music.",
  "Считаю…": "Calculating…",
  "Топ": "Top",
  "Топ дня": "Top today",
  "Тренд": "Trend",
  "Тренд запущен": "Trend started",
  "Тренды": "Trends",
  "Тренды и модели": "Trends and models",
  "Тренды скоро появятся здесь.": "Trends will appear here soon.",
  "Фото": "Photo",
  "Что создаём?": "What are we creating?",
  "Эта модель больше недоступна": "This model is no longer available",
  "Язык интерфейса": "Interface language",
  "Как в Telegram": "Same as Telegram",
  "Русский": "Russian",
  "Аккаунт ROXY": "ROXY account",
  "Управляйте уведомлениями, языком и видимостью профиля. Telegram-имя и username остаются синхронизированы с Telegram.": "Manage notifications, language, and profile visibility. Your Telegram name and username stay synced with Telegram.",
  "Язык переключается сверху рядом с балансом. Здесь можно настроить уведомления и видимость профиля.": "Switch the language at the top next to your balance. Configure notifications and profile visibility here.",
  "Системные уведомления": "System notifications",
  "Результаты, платежи и важные события": "Results, payments, and important events",
  "Новости и предложения": "News and offers",
  "Новые возможности ROXY и промо": "New ROXY features and promos",
  "Показывать профиль в рекомендациях": "Show profile in recommendations",
  "Разрешить другим пользователям находить ваш профиль": "Allow other users to discover your profile",
  "Сохранить": "Save",
  "Сохраняю…": "Saving…",
  "Настройки сохранены.": "Settings saved.",
  "Не удалось загрузить настройки": "Could not load settings",
  "Не удалось сохранить настройки": "Could not save settings",
  "Пополнения ROX": "ROX top-ups",
  "Способ оплаты": "Payment method",
  "ЮKassa — оплата в рублях. Доступный способ выберите на защищённой странице оплаты.": "YooKassa — payment in rubles. Choose an available method on the secure checkout page.",
  "ЮKassa — основной способ оплаты. Lava Top доступна как резерв, CryptoBot — для оплаты криптовалютой.": "YooKassa is the primary payment method. Lava Top is available as a backup, and CryptoBot for crypto payments.",
  "Пополнение сейчас недоступно. Попробуйте ещё раз позже.": "Top-up is currently unavailable. Please try again later.",
  "Не удалось загрузить историю пополнений. Обновите экран или попробуйте позже.": "Could not load top-up history. Refresh the screen or try again later.",
  "Не удалось создать оплату": "Could not create payment",
  "Не удалось открыть платёжную ссылку": "Could not open payment link",
  "Не удалось обновить статус оплаты": "Could not update payment status",
  "Недоступно": "Unavailable",
  "Пакет недоступен": "Package unavailable",
  "Проверить статус": "Check status",
  "Создаю оплату…": "Creating payment…",
  "Оплата подтверждена, ROX начислены.": "Payment confirmed, ROX credited.",
  "Оплата уже подтверждена, ROX начислены.": "Payment already confirmed, ROX credited.",
  "Оплата создана. После оплаты вернитесь сюда и нажмите «Проверить статус».": "Payment created. After paying, return here and tap “Check status”.",
  "Оплата уже зарегистрирована, но ссылка ещё не получена. Второй счёт не создаём — проверьте статус в истории ниже.": "The payment is already registered, but the link has not arrived yet. We won't create a second invoice — check its status in the history below.",
  "Предыдущая попытка оплаты уже зарегистрирована. Второй счёт не создаём — проверьте её статус в истории ниже.": "The previous payment attempt is already registered. We won't create a second invoice — check its status in the history below.",
  "CryptoBot — основной крипто-способ. На странице счёта выберите удобную монету и сеть.": "CryptoBot is the primary crypto method. Choose a coin and network on the invoice page.",
  "2328 — дополнительный крипто-способ. На странице оплаты выберите удобную монету и сеть.": "2328 is an additional crypto method. Choose a coin and network on the payment page.",
  "Email для чека без + и дефиса": "Receipt email without + or hyphen",
  "Промпт по фото / видео": "Prompt from photo / video",
  "Промпты": "Prompts",
  "Режим промпта": "Prompt mode",
  "Анализ": "Analysis",
  "Анализирую…": "Analyzing…",
  "Добавить фото": "Add photo",
  "Добавить видео до 30 МБ": "Add video up to 30 MB",
  "Фото загружено · заменить": "Photo uploaded · replace",
  "Видео загружено · заменить": "Video uploaded · replace",
  "Видео должно быть до 30 МБ": "Video must be up to 30 MB",
  "Загрузите видео": "Upload a video",
  "Добавьте фото или описание": "Add a photo or description",
  "Загружаю…": "Uploading…",
  "Загрузите референс, при желании уточните задачу — ROXY разберёт визуал, движение и камеру и соберёт готовый промпт.": "Upload a reference and optionally clarify the task — ROXY will analyze the visuals, motion, and camera and build a ready-to-use prompt.",
  "Например: особенно точно передай движение камеры и финальный кадр": "For example: reproduce the camera movement and final frame especially accurately",
  "Необязательно: что особенно важно сохранить из фото": "Optional: what is especially important to preserve from the photo",
  "Опишите сцену": "Describe the scene",
  "Что важно сохранить": "What to preserve",
  "Что исключить": "What to exclude",
  "Создать промпт": "Create prompt",
  "Промпт RU": "Prompt RU",
  "Промпт EN": "Prompt EN",
  "Копировать": "Copy",
  "Скопировано ✓": "Copied ✓",
  "Не удалось скопировать промпт. Выделите текст вручную.": "Could not copy the prompt. Select the text manually.",
  "Не удалось загрузить файл": "Could not upload file",
  "Не удалось обработать файл. Загрузите его ещё раз и повторите.": "Could not process the file. Upload it again and retry.",
  "Не удалось подготовить промпт": "Could not prepare prompt",
  "Не удалось восстановить промпт": "Could not restore prompt",
  "Промпт всё ещё готовится. Можно закрыть окно — результат восстановится при следующем открытии.": "The prompt is still being prepared. You can close the window — the result will be restored next time you open it.",
  "Ключевые детали": "Key details",
  "Стиль": "Style",
  "Сценарий": "Scenario",
  "Камера": "Camera",
  "Динамика": "Motion",
  "Звук": "Sound",
  "Уточнение": "Refinement",
  "Рекомендация": "Recommendation",
  "Профиль автора": "Author profile",
  "На основе работы": "Based on a work",
  "Показать описание": "Show description",
  "Будет видно в публикации только если включить": "It will be visible in the publication only when enabled",
  "Примеры": "References",
  "Обсуждение": "Discussion",
  "Стоимость": "Cost",
  "Итог": "Summary",
  "Режим": "Mode",
  "Все фичи ROXY": "All ROXY features",
  "Помощь ROXY": "ROXY help",
  "Получить ROX": "Get ROX",
  "Доход и выплаты": "Earnings and payouts",
  "Мои подписки": "My subscriptions",
  "Управление работами": "Manage works",
  "Действия с результатами": "Result actions",
  "Creator-партнёрство": "Creator partnership",
  "Мои настройки": "My presets",
  "Скачать результаты": "Download results",
  "Конфиденциальность": "Privacy",
  "Правила": "Rules",
  "Добро пожаловать": "Welcome"
};


Object.assign(RU_TO_EN, {
  "Автор ROXY": "ROXY Creator",
  "Выбрать файл": "Choose file",
  "Начислений пока нет.": "No rewards yet.",
  "Откройте через Telegram для запуска": "Open in Telegram to start",
  "Скоро": "Coming soon",

  "Введите код — бонус сразу зачислится на общий баланс ROX.": "Enter a code — the bonus will be credited to your ROX balance immediately.",
  "Не удалось применить промокод": "Could not apply promo code",
  "Применить промокод": "Apply promo code",
  "Проверяю…": "Checking…",
  "Промокод": "Promo code",

  "Восстановить": "Restore",
  "Не удалось восстановить работу": "Could not restore work",
  "Не удалось загрузить историю": "Could not load history",
  "Не удалось скрыть работу": "Could not hide work",
  "Скрытие убирает работу из обычной истории, но не удаляет генерацию. Её всегда можно восстановить.": "Hiding removes a work from regular history but does not delete the generation. You can restore it at any time.",
  "Скрыть": "Hide",

  "Готовый сценарий ROXY с описанием и настройками.": "A ready-made ROXY scenario with description and settings.",
  "Добавить референсы": "Add references",
  "Загружаю сценарий": "Loading scenario",
  "Копирую…": "Copying…",
  "Не удалось загрузить референс": "Could not upload reference",
  "Не удалось открыть тренд": "Could not open trend",
  "Не удалось поделиться трендом": "Could not share trend",
  "Не удалось скопировать ссылку тренда": "Could not copy trend link",
  "Открываю Telegram…": "Opening Telegram…",
  "Поделиться трендом": "Share trend",
  "Референсы не нужны — сценарий можно запустить сразу.": "No references are required — you can start the scenario right away.",
  "Сгенерировать бесплатно": "Generate for free",
  "Скопировать ссылку тренда": "Copy trend link",
  "Тренд не выбран": "No trend selected",
  "изображение": "image",
  "изображения": "images",

  "AI-анализ сцены недоступен": "AI scene analysis is unavailable",
  "Ваш ракурс 1": "Your angle 1",
  "Ваши загруженные ракурсы": "Your uploaded angles",
  "Ваши ракурсы": "Your angles",
  "Вес": "Weight",
  "Выберите фотографии": "Choose photos",
  "Выберите фотографию": "Choose a photo",
  "Добавить свои фото": "Add your photos",
  "Загружаем…": "Uploading…",
  "Загрузить": "Upload",
  "Можно добавить не больше 5 фото": "You can add up to 5 photos",
  "Не удалось загрузить ваши фото": "Could not upload your photos",
  "Не удалось получить фото из Pinterest": "Could not get the photo from Pinterest",
  "ПОВТОР ПО РЕФЕРЕНСУ": "RECREATE FROM REFERENCE",
  "Повтори фото с Pinterest": "Recreate a Pinterest photo",
  "Понравилось фото? Сделаем тебя в нём — сохраним сцену, позу, свет и композицию.": "Like the photo? We'll put you into it while preserving the scene, pose, lighting, and composition.",
  "Разбираем референс…": "Analyzing reference…",
  "Референс": "Reference",
  "Референс сцены": "Scene reference",
  "Рост": "Height",
  "Создать →": "Create →",
  "Создаём…": "Creating…",
  "Считаем…": "Calculating…",
  "Удалить референс": "Remove reference",
  "ссылка на пин с Pinterest": "Pinterest pin link",

  "ID аккаунта": "Account ID",
  "Авторы и отдельная лента их работ": "Creators and a separate feed of their works",
  "Аккаунт": "Account",
  "Активировать код и получить ROX": "Activate a code and get ROX",
  "Баланс, активность и все пользовательские возможности backend в одном месте.": "Balance, activity, and all account features in one place.",
  "Вывод денег и перевод партнёрского баланса в ROX": "Withdraw earnings or transfer partner balance to ROX",
  "Действия с работами": "Work actions",
  "Заявка на индивидуальные условия для авторов": "Apply for custom creator terms",
  "Мои пресеты": "My presets",
  "Мой ROXY": "My ROXY",
  "Не удалось загрузить профиль": "Could not load profile",
  "Оригинальные файлы из собственного хранилища ROXY": "Original files from ROXY storage",
  "Пакеты, бонусные ROX и проверка незавершённых оплат": "Packages, bonus ROX, and pending payment checks",
  "Партнёрский доход": "Partner earnings",
  "Повторить, изменить, оживить или сменить параметры": "Repeat, edit, animate, or change settings",
  "Поддержка": "Support",
  "Подписки": "Subscriptions",
  "Пополнения и статусы": "Top-ups and statuses",
  "Результаты, платежи, промокоды и важные события": "Results, payments, promo codes, and important events",
  "Скрыть работу или восстановить её": "Hide or restore a work",
  "Создать обращение или продолжить диалог": "Create a support request or continue a conversation",
  "Сохранённые модели, параметры и референсы": "Saved models, settings, and references",
  "Уведомления": "Notifications",
  "Управление историей": "Manage history",
  "Язык, уведомления и видимость профиля": "Language, notifications, and profile visibility",

  "Для авторов": "For creators",
  "Индивидуальные условия для каналов и авторов. Заявка проверяется вручную, а согласованные ROX начисляются через официальный партнёрский контур.": "Custom terms for channels and creators. Applications are reviewed manually, and approved ROX are credited through the official partner flow.",
  "Название канала": "Channel name",
  "Не удалось загрузить статус партнёрства": "Could not load partnership status",
  "Не удалось отправить заявку": "Could not submit application",
  "Обзоры, интеграции, контент для ROXY…": "Reviews, integrations, content for ROXY…",
  "Отправить заявку": "Submit application",
  "Расскажите о канале и идее сотрудничества": "Tell us about your channel and collaboration idea",

  "Все обращения сохраняются в одном месте. Можно продолжить диалог, закрыть вопрос или переоткрыть его позже.": "All support requests stay in one place. You can continue the conversation, close an issue, or reopen it later.",
  "Вы": "You",
  "Написать ответ": "Write a reply",
  "Не удалось загрузить обращения": "Could not load support requests",
  "Не удалось обновить обращение": "Could not update support request",
  "Не удалось открыть обращение": "Could not open support request",
  "Не удалось отправить сообщение": "Could not send message",
  "Не удалось создать обращение": "Could not create support request",
  "Опишите, что произошло": "Describe what happened",
  "Поддержка ROXY": "ROXY Support",
  "Создать обращение": "Create request",

  "AI РЕФЕРЕНС": "AI REFERENCE",
  "Взрослый": "Adult",
  "Главный набор инструментов для подготовки референса перед дальнейшей генерацией.": "The main toolkit for preparing a reference before further generation.",
  "Главный старт": "Main start",
  "Детский": "Child",
  "Для администратора": "For admin",
  "Для животных": "For pets",
  "Добавьте готовый референс": "Add a ready reference",
  "Добавьте исходные фото": "Add source photos",
  "Добавьте фото для улучшения": "Add a photo to enhance",
  "Загрузите фото, проверьте настройки и запустите. Результат появится в истории ROXY.": "Upload photos, review the settings, and start. The result will appear in ROXY history.",
  "Макияж, причёска, цвет волос и другие точечные изменения готового референса.": "Makeup, hairstyle, hair color, and other targeted edits to a ready reference.",
  "Можно загрузить до 4 фотографий. Лучше добавить чёткий фронтальный кадр и ещё 1–2 ракурса.": "You can upload up to 4 photos. A clear front-facing shot plus 1–2 additional angles works best.",
  "Не удалось загрузить фотографию": "Could not upload photo",
  "Не удалось запустить обработку": "Could not start processing",
  "Нужна одна фотография. Исходник останется без изменений.": "One photo is required. The original will remain unchanged.",
  "Повышает детализацию и резкость, сохраняя лицо, композицию и исходный образ.": "Improves detail and sharpness while preserving the face, composition, and original look.",
  "Применить изменения": "Apply changes",
  "Редактор референса": "Reference editor",
  "Своя инструкция": "Custom instruction",
  "Соберите чистый референс человека, ребёнка или питомца из ваших фотографий.": "Build a clean reference of a person, child, or pet from your photos.",
  "Создание референса": "Reference creation",
  "Создать референс": "Create reference",
  "Сохраняем внешность и естественные черты": "Preserve appearance and natural features",
  "Сохраняем возраст и детские черты без взрослой стилизации": "Preserve age and childlike features without adult styling",
  "Сохраняем породу, окрас, отметины и пропорции": "Preserve breed, coloring, markings, and proportions",
  "Считаю стоимость…": "Calculating cost…",
  "Улучшение качества HD": "HD quality enhancement",
  "Улучшить в HD": "Enhance in HD",
  "Улучшить качество HD": "Enhance HD quality",
  "＋ Добавить фотографии": "＋ Add photos",
  "＋ Добавить фотографию": "＋ Add photo",

  "Когда результат уже перенесён в собственное хранилище ROXY, скачивание идёт через защищённую ссылку с корректным именем файла.": "Once a result is stored in ROXY storage, it downloads through a protected link with the correct filename.",
  "Не удалось загрузить файлы": "Could not load files",
  "Файлы": "Files",

  "ЮKassa": "YooKassa",

  "Добавить 2–20 изображений": "Add 2–20 images",
  "Добавьте описание": "Add a description",
  "Добавьте от 2 до 20 изображений": "Add 2 to 20 images",
  "Загрузите 2–20 изображений, добавьте одно описание и запустите их одной задачей.": "Upload 2–20 images, add one instruction, and run them as a single batch.",
  "Запустить пакет": "Start batch",
  "Не удалось загрузить пакеты": "Could not load batches",
  "Не удалось запустить пакет": "Could not start batch",
  "Не удалось открыть Batch": "Could not open Batch",
  "Не удалось повторить ошибки": "Could not retry failed items",
  "Не удалось рассчитать пакет": "Could not calculate batch",
  "Пакет": "Batch",
  "Пакетная обработка": "Batch processing",
  "Работаю…": "Working…",
  "Рассчитать стоимость": "Calculate cost",
  "Частично готово": "Partially complete",
  "Что изменить в каждом изображении?": "What should be changed in each image?",

  "ROXY не сохранила референс. Попробуйте ещё раз.": "ROXY did not save the reference. Please try again.",
  "Берём идею и настройки исходной работы, а референсы добавляете вы. Файлы автора в вашу генерацию не переносятся.": "We use the idea and settings from the original work, while you add your own references. The creator's files are never copied into your generation.",
  "Выбрать файлы": "Choose files",
  "Для администратора бесплатно": "Free for admin",
  "Добавить ещё": "Add more",
  "Добавить фото, видео или аудио": "Add photo, video, or audio",
  "Добавьте референсы": "Add references",
  "Добавьте свои референсы": "Add your references",
  "Загрузите аудиофайл": "Upload an audio file",
  "Загрузите изображение": "Upload an image",
  "Замените референсы автора": "Replace the creator's references",
  "Исходная работа": "Original work",
  "Не удалось запустить повтор": "Could not start repeat",
  "Не удалось определить работу для повтора": "Could not identify the work to repeat",
  "Не удалось подготовить повтор": "Could not prepare repeat",
  "Не удалось скопировать ссылку повтора": "Could not copy repeat link",
  "Повтор из ленты": "Repeat from feed",
  "Повтор работы": "Repeat work",
  "Расчёт готов": "Estimate ready",
  "Своя версия работы": "Your version of the work",
  "Скопировать ссылку повтора": "Copy repeat link",
  "Ссылка повтора пока недоступна": "Repeat link is not available yet",
  "своих аудиофайла": "your audio files",
  "своих видео": "your videos",
  "своих фото": "your photos",
  "свой аудиофайл": "your audio file",
  "своё видео": "your video",
  "своё фото": "your photo",

  "Всё просмотрено": "All read",
  "Не удалось загрузить уведомления": "Could not load notifications",
  "Не удалось отметить уведомление": "Could not mark notification",
  "Не удалось отметить уведомления": "Could not mark notifications",
  "Новая": "New",
  "Обновляю…": "Refreshing…",
  "Прочитать все": "Mark all as read",
  "Статусы генераций, промокоды, выплаты и важные сообщения ROXY.": "Generation statuses, promo codes, payouts, and important ROXY messages.",

  "Аудио": "Audio",
  "Базовый промпт пресета": "Preset base prompt",
  "Без фиксированного промпта": "No fixed prompt",
  "Изменить набор": "Edit preset",
  "Не удалось загрузить пресеты": "Could not load presets",
  "Не удалось сохранить пресет": "Could not save preset",
  "Не удалось удалить пресет": "Could not delete preset",
  "Новый пресет": "New preset",
  "Пресеты": "Presets",
  "Редактирование": "Editing",
  "Создать пресет": "Create preset",
  "Сохранить изменения": "Save changes",
  "Сохранить набор": "Save preset",
  "Сохраняйте модель, промпт, параметры, длительность и библиотеку референсов как повторно используемые наборы.": "Save a model, prompt, settings, duration, and reference library as reusable presets.",

  "Выводятся только партнёрские начисления в ₽ — процент с реально оплаченных заказов ваших рефералов. ROX — внутренняя валюта ROXY и на карту не выводится.": "Only partner earnings in RUB can be withdrawn — a share of orders actually paid by your referrals. ROX is ROXY's internal currency and cannot be withdrawn to a card.",
  "Выполняю…": "Processing…",
  "Заявка на выплату создана": "Payout request created",
  "Заявка отменена": "Request canceled",
  "Карта / СБП / другие согласованные реквизиты": "Card / SBP / other agreed payment details",
  "Не удалось загрузить партнёрский баланс": "Could not load partner balance",
  "Не удалось отменить выплату": "Could not cancel payout",
  "Не удалось перевести баланс в ROX": "Could not transfer balance to ROX",
  "Не удалось создать выплату": "Could not create payout",
  "Перевести в ROX": "Transfer to ROX",
  "Создать заявку": "Create request",
  "Создаю…": "Creating…",

  "Действия": "Actions",
  "Не удалось загрузить готовые работы": "Could not load finished works",
  "Не удалось загрузить действия": "Could not load actions",
  "Повторить, изменить, оживить, сменить промпт или параметры — ROXY показывает только совместимые действия и модели.": "Repeat, edit, animate, change the prompt or settings — ROXY shows only compatible actions and models.",
  "Свернуть": "Collapse",

  "Не удалось загрузить подписки": "Could not load subscriptions",
  "Не удалось отписаться": "Could not unsubscribe",
  "Отписаться": "Unsubscribe",
  "Профиль скрыт": "Profile hidden",
  "Работы авторов, на которых вы подписаны, собраны в отдельную ленту.": "Works from creators you follow are collected in a separate feed.",
  "Сообщество": "Community"
});


Object.assign(RU_TO_EN, {
  "1 · Идея": "1 · Idea",
  "1 линия": "Line 1",
  "1–5 ваших фото": "1–5 of your photos",
  "2 · Ваши референсы": "2 · Your references",
  "2 линия": "Line 2",
  "3 · Запуск": "3 · Launch",
  "AI-разбор недоступен — повторим сцену напрямую по референсу.": "AI analysis is unavailable — we'll recreate the scene directly from the reference.",
  "JPG, PNG, HEIC и другие изображения, которые принимает ROXY": "JPG, PNG, HEIC, and other image formats accepted by ROXY",
  "Lava Top · резерв": "Lava Top · backup",
  "ROX / файл": "ROX / file",
  "ROX всего": "Total ROX",
  "ROX на балансе": "ROX balance",
  "ROX начислено": "ROX credited",
  "ROXY использует исходный промпт на сервере, но не раскрывает его. Вам остаётся заменить референсы своими.": "ROXY uses the original prompt on the server without revealing it. You only need to replace the references with your own.",
  "ROXY подстроит правила сохранения внешности под тип референса.": "ROXY will adapt identity-preservation rules to the reference type.",
  "Аккаунт и сервисы": "Account and services",
  "Аудитория": "Audience",
  "Библиотека": "Library",
  "Быстрая связь": "Quick contact",
  "В повтор попадут только файлы из вашего аккаунта ROXY. Референсы исходной публикации не копируются.": "Only files from your ROXY account will be used in the repeat. References from the original publication are not copied.",
  "ВЕС": "WEIGHT",
  "Вернуться в ленту": "Back to feed",
  "Возможности": "Features",
  "Все уведомления": "All notifications",
  "Вставь ссылку на пин (pinterest.com/pin/... или pin.it/...) — сами вытащим картинку и используем её как сцену.": "Paste a pin link (pinterest.com/pin/... or pin.it/...) — we'll fetch the image and use it as the scene.",
  "Вы пока ни на кого не подписаны.": "You are not following anyone yet.",
  "Выберите": "Choose",
  "Вывести деньги": "Withdraw money",
  "Выплата": "Payout",
  "Выплаты": "Payouts",
  "Генерация запускается только после нажатия кнопки. Готовый результат появится в истории.": "Generation starts only after you tap the button. The finished result will appear in history.",
  "Готовые работы": "Finished works",
  "Готовых файлов пока нет.": "No finished files yet.",
  "Длительность целевой сцены": "Target scene duration",
  "Для этой работы дополнительных действий нет.": "No additional actions are available for this work.",
  "Если нужен быстрый ответ, напишите напрямую:": "For a quick response, message us directly:",
  "Загружаем референс из Pinterest…": "Loading reference from Pinterest…",
  "Загружаю профиль…": "Loading profile…",
  "Загрузка…": "Loading…",
  "Закрыть обращение": "Close request",
  "Закрыть окно": "Close window",
  "Заполните только свои данные. Скрытый промпт останется скрытым.": "Enter only your own data. The hidden prompt will remain hidden.",
  "Заявка": "Request",
  "Заявок пока нет.": "No requests yet.",
  "Здесь пока пусто.": "Nothing here yet.",
  "Здесь появятся публикации авторов, на которых вы подпишетесь.": "Publications from creators you follow will appear here.",
  "ИЛИ ВСТАВЬ ССЫЛКУ": "OR PASTE A LINK",
  "ИСТОЧНИК": "SOURCE",
  "Изменить": "Edit",
  "История заявок": "Request history",
  "История переводов": "Transfer history",
  "Исходные фото сильно влияют на результат — используйте чёткие снимки без сильных фильтров.": "Source photos strongly affect the result — use clear shots without heavy filters.",
  "КОГО ВСТАВЛЯЕМ": "WHO TO INSERT",
  "Канал / площадка": "Channel / platform",
  "Кого готовим?": "Who are we preparing?",
  "Комментарий": "Comment",
  "Мои обращения": "My requests",
  "Название": "Name",
  "Написать в поддержку": "Message support",
  "Настройки исходной работы сохранены. ROXY автоматически выберет text/reference режим модели по вашим файлам.": "The original work settings are preserved. ROXY will automatically choose the model's text/reference mode based on your files.",
  "Начисления": "Rewards",
  "Не выбрано": "Not selected",
  "Не получилось создать работу. Попробуйте ещё раз или измените описание.": "Could not create the work. Try again or change the description.",
  "Новое обращение": "New request",
  "Новые работы": "New works",
  "ОТКУДА": "SOURCE",
  "Обращений пока нет.": "No support requests yet.",
  "Описание и подходящие настройки уже перенесены. Если выбрать другую модель, ROXY подготовит форму заново.": "The description and compatible settings have already been transferred. If you choose another model, ROXY will rebuild the form.",
  "Оплата картой сейчас недоступна. Можно пополнить через CryptoBot.": "Card payment is currently unavailable. You can top up via CryptoBot.",
  "Оплатить": "Pay",
  "Оригиналы": "Originals",
  "Основной способ — ЮKassa. Lava Top используйте как резерв, если основной платёж не проходит.": "YooKassa is the primary method. Use Lava Top as a backup if the primary payment does not go through.",
  "Открыть": "Open",
  "Отмена": "Cancel",
  "Отменить": "Cancel",
  "Пакетов пока нет.": "No packages yet.",
  "Партнёрские рубли можно добровольно перевести в ROX для генераций. Это односторонняя конвертация: ROX обратно в деньги не выводятся.": "Partner RUB earnings can be voluntarily converted to ROX for generations. This is one-way: ROX cannot be converted back to money.",
  "Перевести в баланс": "Transfer to balance",
  "Переводов пока нет.": "No transfers yet.",
  "Переоткрыть": "Reopen",
  "Персонализируйте шаблон": "Personalize template",
  "Повтор запущен не будет автоматически — сначала добавьте свои референсы и подтвердите запуск.": "The repeat will not start automatically — first add your references and confirm the launch.",
  "Повторить ошибки": "Retry failed",
  "Подготавливаю повтор…": "Preparing repeat…",
  "Поддержка в Telegram": "Support in Telegram",
  "Показать ещё": "Show more",
  "Пополнение сейчас недоступно.": "Top-up is currently unavailable.",
  "Пополнений пока нет.": "No top-ups yet.",
  "Пополнения": "Top-ups",
  "После запуска задача появится в истории. Можно закрыть Mini App — генерация продолжится на сервере.": "After launch, the task will appear in history. You can close the Mini App — generation will continue on the server.",
  "Последние пакеты": "Recent batches",
  "Последняя заявка": "Latest request",
  "Предложить сотрудничество": "Propose a collaboration",
  "Пресетов пока нет.": "No presets yet.",
  "Промпт автора скрыт": "Creator prompt is hidden",
  "РЕФЕРЕНС": "REFERENCE",
  "РОСТ": "HEIGHT",
  "Разбираем сцену, позу, свет и эмоцию…": "Analyzing scene, pose, lighting, and emotion…",
  "Реквизиты": "Payment details",
  "Рост и вес нужны, чтобы руки, шея и пропорции тела совпали с тобой. Основную форму тела модель берёт с твоих фото.": "Height and weight help match your arms, neck, and body proportions. The model takes your main body shape from your photos.",
  "Скопировать профиль": "Copy profile",
  "Скопировать реферальную ссылку": "Copy referral link",
  "Сначала добавьте все свои референсы, которые нужны для этой работы.": "First add all your references required for this work.",
  "Сообщение": "Message",
  "Сохранённые пресеты": "Saved presets",
  "Сохранённые референсы": "Saved references",
  "Средние просмотры": "Average views",
  "Ссылка": "Link",
  "Ссылка повтора повреждена или устарела.": "The repeat link is damaged or expired.",
  "Стоимость · формат наследуется с референса": "Cost · format is inherited from the reference",
  "Сумма, ₽": "Amount, RUB",
  "ТЫ": "YOU",
  "Тема": "Topic",
  "Убрать": "Remove",
  "Уведомлений пока нет.": "No notifications yet.",
  "Удалить": "Delete",
  "Формат сотрудничества": "Collaboration format",
  "Центр событий": "Activity center",
  "Чат партнёров": "Partner chat",
  "Что изменить?": "What should be changed?",
  "ЮKassa сейчас недоступна — включён резервный способ Lava Top.": "YooKassa is currently unavailable — Lava Top backup is enabled.",
  "базовые ROX": "base ROX",
  "баланс": "balance",
  "бонус": "bonus",
  "в работе": "in progress",
  "генераций": "generations",
  "готово": "ready",
  "доступно": "available",
  "заработано": "earned",
  "изображений": "images",
  "итого ROX": "total ROX",
  "кг": "kg",
  "лайков": "likes",
  "ожидается": "pending",
  "ошибок": "failed",
  "подписчиков": "followers",
  "публикаций": "publications",
  "работ": "works",
  "см": "cm",
  "сцена, свет и поза считаны с референса": "scene, lighting, and pose analyzed from the reference",
  "успешно": "successful",
  "фото-референс": "photo reference",
  "← Выбрать другой сценарий": "← Choose another scenario"
});


Object.assign(RU_TO_EN, {
  "NSFW-проверка": "NSFW check",
  "Авторасширение промпта": "Auto-expand prompt",
  "В простом режиме Suno промпт должен быть не длиннее 500 символов": "In Suno simple mode, the prompt must be no longer than 500 characters",
  "Вернуть последний кадр": "Return last frame",
  "Видео движения": "Motion video",
  "Видео-референсы": "Video references",
  "Водяной знак": "Watermark",
  "Детали": "Details",
  "Длительность для расчёта": "Billing duration",
  "Длительность референс-видео": "Reference video duration",
  "Дополнительно": "Advanced",
  "Загрузить изображение": "Upload image",
  "Зафиксировать камеру": "Lock camera",
  "Из Grok-задачи": "From Grok task",
  "Изображение": "Image",
  "Изображения": "Images",
  "Источник фона": "Background source",
  "Исходная Kie-задача": "Source Kie task",
  "Исходный клип": "Source clip",
  "Качество": "Quality",
  "Количество вариантов": "Number of variants",
  "Количество изображений": "Number of images",
  "Количество расширений": "Number of extensions",
  "Мультиреференсы": "Multiple references",
  "Настройки аудио": "Audio settings",
  "Негативный промпт": "Negative prompt",
  "Ногти": "Nails",
  "Одежда": "Clothing",
  "Опишите желаемый результат": "Describe the desired result",
  "Оплачиваемая длина расширения": "Billable extension length",
  "Ориентация персонажа": "Character orientation",
  "Первый + последний": "First + last",
  "Первый кадр": "First frame",
  "Последний кадр": "Last frame",
  "Последовательная генерация": "Sequential generation",
  "Причёска": "Hairstyle",
  "Продолжить видео": "Extend video",
  "Размер": "Size",
  "Размер изображения": "Image size",
  "Разрешение": "Resolution",
  "Разрешение изображения": "Image resolution",
  "Референс-аудио": "Audio reference",
  "Референс-видео": "Video reference",
  "Референс-голос": "Voice reference",
  "Референс-изображение": "Image reference",
  "Референс-изображения": "Image references",
  "Референсы": "References",
  "Своё": "Custom",
  "Сгенерировать звук": "Generate audio",
  "Случайный": "Random",
  "Соотношение сторон": "Aspect ratio",
  "Текст": "Text",
  "Точка расширения": "Extension point",
  "Управляющее аудио": "Control audio",
  "Фон": "Background",
  "Формат результата": "Output format",
  "Фото персонажа": "Character photo",
  "Цвет волос": "Hair color",
  "Что исключить из результата": "What to exclude from the result",
  "с": "s"
});


Object.assign(RU_TO_EN, {
  "Партнёрская программа": "Partner program",
  "Создавай фото и видео": "Create photos and videos",
  "Шаблоны, тренды и работы сообщества": "Templates, trends, and community works",
  "Расширенные настройки": "Advanced settings",
  "День рождения": "Birthday",
  "То, что сейчас гуляет в Instagram": "What's trending on Instagram right now",
  "Фото и видео для поздравлений и праздничных сюжетов": "Photos and videos for greetings and festive stories"
});

const EN_TO_RU = Object.fromEntries(Object.entries(RU_TO_EN).map(([ru, en]) => [en, ru])) as Record<string, string>;

type Pattern = [RegExp, (match: RegExpMatchArray) => string];

const RU_PATTERNS: Pattern[] = [
  [/^(\d+(?:[.,]\d+)?) моделей$/, (m) => `${m[1]} models`],
  [/^(\d+(?:[.,]\d+)?) вариантов$/, (m) => `${m[1]} variants`],
  [/^от (.+)$/, (m) => `from ${m[1]}`],
  [/^Баланс: (.+)$/, (m) => `Balance: ${m[1]}`],
  [/^Минимум (\d+) сек\.$/, (m) => `Minimum ${m[1]} sec.`],
  [/^Максимум (\d+) сек\.$/, (m) => `Maximum ${m[1]} sec.`],
  [/^Количество — от 1 до (\d+)$/, (m) => `Quantity — 1 to ${m[1]}`],
  [/^Линия (\d+)$/, (m) => `Line ${m[1]}`],
  [/^(\d+) загружено$/, (m) => `${m[1]} uploaded`],
  [/^Открыть пример (\d+)$/, (m) => `Open reference ${m[1]}`],
  [/^Открыть видео-пример (\d+)$/, (m) => `Open video reference ${m[1]}`],
  [/^Слайд (\d+)$/, (m) => `Slide ${m[1]}`],
  [/^(\d+) непрочитанных$/, (m) => `${m[1]} unread`]
];

const EN_PATTERNS: Pattern[] = [
  [/^(\d+(?:[.,]\d+)?) models$/, (m) => `${m[1]} моделей`],
  [/^(\d+(?:[.,]\d+)?) variants$/, (m) => `${m[1]} вариантов`],
  [/^from (.+)$/, (m) => `от ${m[1]}`],
  [/^Balance: (.+)$/, (m) => `Баланс: ${m[1]}`],
  [/^Minimum (\d+) sec\.$/, (m) => `Минимум ${m[1]} сек.`],
  [/^Maximum (\d+) sec\.$/, (m) => `Максимум ${m[1]} сек.`],
  [/^Quantity — 1 to (\d+)$/, (m) => `Количество — от 1 до ${m[1]}`],
  [/^Line (\d+)$/, (m) => `Линия ${m[1]}`],
  [/^(\d+) uploaded$/, (m) => `${m[1]} загружено`],
  [/^Open reference (\d+)$/, (m) => `Открыть пример ${m[1]}`],
  [/^Open video reference (\d+)$/, (m) => `Открыть видео-пример ${m[1]}`],
  [/^Slide (\d+)$/, (m) => `Слайд ${m[1]}`],
  [/^(\d+) unread$/, (m) => `${m[1]} непрочитанных`]
];

function translateCore(value: string, language: UiLanguage): string {
  const direct = language === "en" ? RU_TO_EN[value] : EN_TO_RU[value];
  if (direct) return direct;
  const patterns = language === "en" ? RU_PATTERNS : EN_PATTERNS;
  for (const [pattern, format] of patterns) {
    const match = value.match(pattern);
    if (match) return format(match);
  }

  const monthPairs = [
    ["янв.", "Jan"], ["февр.", "Feb"], ["мар.", "Mar"], ["апр.", "Apr"],
    ["мая", "May"], ["июн.", "Jun"], ["июл.", "Jul"], ["авг.", "Aug"],
    ["сент.", "Sep"], ["окт.", "Oct"], ["нояб.", "Nov"], ["дек.", "Dec"],
  ] as const;
  let withLocaleDates = value;
  for (const [ru, en] of monthPairs) {
    withLocaleDates = language === "en"
      ? withLocaleDates.replaceAll(ru, en)
      : withLocaleDates.replaceAll(en, ru);
  }
  return withLocaleDates;
}

export function translateUiText(value: string, language: UiLanguage): string {
  if (!value) return value;
  const match = value.match(/^(\s*)([\s\S]*?)(\s*)$/);
  if (!match) return value;
  const translated = translateCore(match[2], language);
  return translated === match[2] ? value : `${match[1]}${translated}${match[3]}`;
}

export function resolveUiLanguage(preference: string | null | undefined, telegramLanguageCode?: string | null): UiLanguage {
  if (preference === "ru" || preference === "en") return preference;
  const telegramLanguage = String(telegramLanguageCode || "").toLowerCase();
  if (!telegramLanguage) return "ru";
  return telegramLanguage.startsWith("ru") ? "ru" : "en";
}
