from app.services.model_spec_audit_fixes import install_model_spec_audit_fixes
from app.services.provider_contract_guards import install_provider_contract_guards
from app.services.provider_contract_sync import install_provider_contract_sync

install_provider_contract_sync()
install_provider_contract_guards()
install_model_spec_audit_fixes()
