from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
import logging
import mimetypes
from pathlib import Path

from aiogram import Bot
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse
from fastapi.staticfiles import StaticFiles
from redis.asyncio import Redis

from app.api.card_webhooks import router as card_webhook_router
from app.api.health import router as health_router
from app.api.internal_admin import router as internal_admin_router
from app.api.metrics import router as metrics_router
from app.api.router import api_router
from app.api.v1.batches import router as batch_router
from app.api.webhooks import router as webhook_router
from app.bot.dispatcher import create_dispatcher
from app.core.config import settings
from app.core.http_observability import RequestObservabilityMiddleware
from app.core.http_security import SecurityHeadersMiddleware
from app.core.logging import configure_logging
from app.core.observability import configure_telemetry, shutdown_telemetry
from app.db.session import SessionFactory, engine
from app.services.abuse_protection import ProtectionBackendUnavailable, ResourcePolicyError
from app.services.admin_pricing import AdminPricingService
from app.services.feed_static import FeedStaticStorage
from app.services.notification_events import register_notification_events
from app.services.reference_static import ReferenceStaticStorage

configure_logging()
register_notification_events()
logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    redis = Redis.from_url(settings.redis_url, decode_responses=True)
    app.state.redis = redis
    app.state.bot = None
    app.state.dispatcher = None
    app.state.bot_has_main_web_app = False
    FeedStaticStorage.ensure_root()
    ReferenceStaticStorage.ensure_root()

    if settings.app_env.lower() != "test":
        async with SessionFactory() as session:
            await AdminPricingService.hydrate_runtime(session)

    if settings.bot_token:
        bot = Bot(settings.bot_token)
        dispatcher = create_dispatcher(redis)
        app.state.bot = bot
        app.state.dispatcher = dispatcher

        # tanyapi derives public Mini App links from Telegram's live bot identity,
        # not from a potentially stale deployment username. Keep the same contract
        # for every referral/feed/profile/remix link generated by this process.
        try:
            bot_info = await bot.get_me()
            if bot_info.username:
                settings.bot_username = bot_info.username
            app.state.bot_has_main_web_app = bool(
                getattr(bot_info, "has_main_web_app", False)
            )
            if settings.is_production and not app.state.bot_has_main_web_app:
                logger.warning(
                    "Telegram Main Mini App is not enabled for @%s; "
                    "?startapp links will not open until BotFather Configure Mini App is enabled",
                    settings.bot_username or "unknown",
                )
        except Exception:
            logger.exception("Unable to synchronize Telegram bot identity")

        if settings.telegram_webhook_url:
            webhook_url = f"{settings.telegram_webhook_url.rstrip('/')}/webhooks/telegram"
            await bot.set_webhook(
                webhook_url,
                secret_token=settings.telegram_webhook_secret or None,
                allowed_updates=dispatcher.resolve_used_update_types(),
            )

    try:
        yield
    finally:
        dispatcher = app.state.dispatcher
        bot = app.state.bot
        if dispatcher is not None:
            await dispatcher.storage.close()
        if bot is not None:
            await bot.session.close()
        await redis.aclose()
        await engine.dispose()
        shutdown_telemetry()


app = FastAPI(
    title="KSU API",
    version="0.1.0",
    docs_url=None if settings.is_production else "/docs",
    redoc_url=None if settings.is_production else "/redoc",
    lifespan=lifespan,
)
app.add_middleware(SecurityHeadersMiddleware)
app.add_middleware(RequestObservabilityMiddleware)
configure_telemetry(app)


@app.exception_handler(ResourcePolicyError)
async def resource_policy_error(_request: Request, exc: ResourcePolicyError) -> JSONResponse:
    status_code = 503 if isinstance(exc, ProtectionBackendUnavailable) else 429
    return JSONResponse(
        status_code=status_code,
        headers={"Retry-After": str(exc.retry_after)},
        content={
            "detail": str(exc),
            "code": exc.code,
            "retry_after": exc.retry_after,
        },
    )


app.include_router(health_router)
app.include_router(metrics_router)
app.include_router(webhook_router)
app.include_router(card_webhook_router)
app.include_router(internal_admin_router)
app.include_router(api_router)
app.include_router(batch_router, prefix="/api/v1")

web_dir = Path(__file__).resolve().parent / "web"
mini_app_dir = web_dir / "mini_app"
admin_app_dir = web_dir / "admin_app"
mimetypes.add_type("image/webp", ".webp")

# Production Nginx can serve these paths directly. StaticFiles keeps local and
# reverse-proxy-less deployments on the same product-owned URL contract.
app.mount(
    FeedStaticStorage.public_prefix(),
    StaticFiles(directory=FeedStaticStorage.ensure_root()),
    name="feed-static",
)
app.mount(
    ReferenceStaticStorage.public_prefix(),
    StaticFiles(directory=ReferenceStaticStorage.ensure_root()),
    name="reference-static",
)
app.mount("/mini-app", StaticFiles(directory=mini_app_dir, html=True), name="mini-app")
app.mount("/admin-app", StaticFiles(directory=admin_app_dir, html=True), name="admin-app")
